/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int DESC = 9;
  /** RegularExpression Id. */
  int VALUES = 10;
  /** RegularExpression Id. */
  int WHERE = 11;
  /** RegularExpression Id. */
  int SELECT = 12;
  /** RegularExpression Id. */
  int AS = 13;
  /** RegularExpression Id. */
  int FROM = 14;
  /** RegularExpression Id. */
  int REFERENCES = 15;
  /** RegularExpression Id. */
  int CREATE = 16;
  /** RegularExpression Id. */
  int DROP = 17;
  /** RegularExpression Id. */
  int TABLE = 18;
  /** RegularExpression Id. */
  int INSERT = 19;
  /** RegularExpression Id. */
  int INTO = 20;
  /** RegularExpression Id. */
  int DELETE = 21;
  /** RegularExpression Id. */
  int SHOW = 22;
  /** RegularExpression Id. */
  int TABLES = 23;
  /** RegularExpression Id. */
  int PRIMARY = 24;
  /** RegularExpression Id. */
  int FOREIGN = 25;
  /** RegularExpression Id. */
  int KEY = 26;
  /** RegularExpression Id. */
  int SEMICOLON = 27;
  /** RegularExpression Id. */
  int LEFT_PAREN = 28;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 29;
  /** RegularExpression Id. */
  int COMMA = 30;
  /** RegularExpression Id. */
  int UNDERSCORE = 31;
  /** RegularExpression Id. */
  int INT_VALUE = 32;
  /** RegularExpression Id. */
  int SIGN = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int CHAR_STRING = 35;
  /** RegularExpression Id. */
  int DATE_VALUE = 36;
  /** RegularExpression Id. */
  int NNNN = 37;
  /** RegularExpression Id. */
  int NN = 38;
  /** RegularExpression Id. */
  int NULL = 39;
  /** RegularExpression Id. */
  int PERIOD = 40;
  /** RegularExpression Id. */
  int AND = 41;
  /** RegularExpression Id. */
  int OR = 42;
  /** RegularExpression Id. */
  int NOT = 43;
  /** RegularExpression Id. */
  int IS = 44;
  /** RegularExpression Id. */
  int STAR = 45;
  /** RegularExpression Id. */
  int COMP_OP = 46;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 47;
  /** RegularExpression Id. */
  int ALPHABET = 48;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 49;
  /** RegularExpression Id. */
  int QUOTE = 50;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTERS = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"desc\"",
    "\"values\"",
    "\"where\"",
    "\"select\"",
    "\"as\"",
    "\"from\"",
    "\"references\"",
    "\"create\"",
    "\"drop\"",
    "\"table\"",
    "\"insert\"",
    "\"into\"",
    "\"delete\"",
    "\"show\"",
    "\"tables\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"_\"",
    "<INT_VALUE>",
    "<SIGN>",
    "<DIGIT>",
    "<CHAR_STRING>",
    "<DATE_VALUE>",
    "<NNNN>",
    "<NN>",
    "\"null\"",
    "\".\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"is\"",
    "\"*\"",
    "<COMP_OP>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "<NON_QUOTE_CHARACTER>",
    "\"\\\'\"",
    "<NON_QUOTE_SPECIAL_CHARACTERS>",
  };

}
